
name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and Push to Dockerhub
        id: build-docker-image
        run: |
          docker build --build-arg DB_USER=${{ secrets.DB_USER }} --build-arg DB_PASS=${{ secrets.DB_PASS }} -t andreskasekamp/billing-database:latest .
          docker push andreskasekamp/billing-database:latest
